version: "3.0"

services:
  db:
    container_name: task-elevate-db
    image: mongo:7.0.11
    restart: always
    ports:
      - "9002:27017"
    volumes:
      - ./dbData:/data/db
    networks:
      - task_elevate_net

  server:
    container_name: task-elevate-server
    image: node:20.14.0
    restart: always
    volumes:
      - ./server:/usr/src/app
    networks:
      - task_elevate_net
    working_dir: /usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /usr/src/app
        cd /usr/src/app
        npm install
        npm run dev
    ports:
      - "9001:9001"
    depends_on:
      - db

  client:
    container_name: task-elevate-client
    image: node:20.14.0
    restart: always
    volumes:
      - ./client:/app
    networks:
      - task_elevate_net
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /app
        cd /app
        npm install
        npm start
    ports:
      - "9003:3000"
    depends_on:
      - server

networks:
  task_elevate_net:
    driver: bridge
    ipam:
      config:
        - subnet: 7.2.0.0/24
          gateway: 7.2.0.1